#!/usr/bin/env bash
# bootstrap.sh — Interactive setup for {{PROJECT_NAME}}
# Reads onboard.yml at startup via python3 + PyYAML.
# Generated by rhel-devops-skills scaffold (type: hub-student)
#
# Usage:
#   ./bootstrap.sh                    # prod mode (default), interactive
#   ./bootstrap.sh --mode dev         # maintainer/contributor setup
#   ./bootstrap.sh --non-interactive  # use all defaults, no prompts
#   ./bootstrap.sh --check-only       # run validation checks only

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MANIFEST="$SCRIPT_DIR/onboard.yml"

# ─── Colors ──────────────────────────────────────────────────────────────────

if [[ -t 1 ]]; then
    RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
    BLUE='\033[0;34m'; BOLD='\033[1m'; RESET='\033[0m'
else
    RED=''; GREEN=''; YELLOW=''; BLUE=''; BOLD=''; RESET=''
fi

info()    { echo -e "${BLUE}[INFO]${RESET} $*"; }
ok()      { echo -e "  ${GREEN}[OK]${RESET}      $*"; }
fail()    { echo -e "  ${RED}[FAIL]${RESET}    $*"; }
warn_msg(){ echo -e "  ${YELLOW}[WARN]${RESET}    $*"; }

# ─── Prerequisites ───────────────────────────────────────────────────────────

check_python() {
    if ! command -v python3 &>/dev/null; then
        echo "ERROR: python3 is required to parse onboard.yml"
        echo "Install: sudo dnf install -y python3"
        exit 1
    fi
    if ! python3 -c "import yaml" 2>/dev/null; then
        echo "ERROR: PyYAML is required to parse onboard.yml"
        echo "Install: sudo dnf install -y python3-pyyaml"
        exit 1
    fi
}

# ─── Manifest Parsing ────────────────────────────────────────────────────────

read_manifest() {
    local key="$1"
    python3 -c "
import yaml, sys
with open('$MANIFEST') as f:
    data = yaml.safe_load(f)
keys = '$key'.split('.')
val = data
for k in keys:
    if isinstance(val, dict):
        val = val.get(k, '')
    else:
        val = ''
        break
print(val if val else '')
"
}

# ─── Main ────────────────────────────────────────────────────────────────────

main() {
    check_python

    if [[ ! -f "$MANIFEST" ]]; then
        echo "ERROR: onboard.yml not found in $SCRIPT_DIR"
        echo "This file declares the project's prerequisites and configuration."
        exit 1
    fi

    local project_name
    project_name="$(read_manifest name)"
    echo ""
    echo -e "${BOLD}=== $project_name Onboarding ===${RESET}"
    echo "$(read_manifest description)"
    echo ""

    info "This script will:"
    echo "  1. Check and install prerequisites"
    echo "  2. Configure your environment"
    echo "  3. Validate readiness"
    echo ""
    info "Hub-student workshop topology: 1 hub + {{NUM_STUDENTS}} student clusters"
    echo ""

    # TODO: Implement full manifest-driven onboarding phases
    # See the 'onboard' skill for the complete runtime implementation
    info "For full interactive onboarding, use the 'onboard' AI skill."
    info "Or run: make setup"
}

main "$@"
