# {{PROJECT_NAME}} — Hub-Student Workshop
# Generated by rhel-devops-skills scaffold (type: hub-student)

PROJECT_TYPE := hub-student
WORKSHOP_LIB ?= $(HOME)/.local/share/rhel-devops-skills

DEPLOY_SCRIPT := scripts/deploy-workshop.sh
TEARDOWN_SCRIPT := scripts/teardown-workshop.sh
QUOTA_SCRIPT := scripts/check-quota.sh
BOOTSTRAP_SCRIPT := bootstrap.sh

include $(WORKSHOP_LIB)/workshop.mk
