# onboard.yml — Project onboarding manifest for {{PROJECT_NAME}}
# Generated by rhel-devops-skills scaffold (type: hub-student)
# Schema: https://github.com/tosin2013/rhel-devops-skills-cli (onboard skill)

name: "{{PROJECT_NAME}}"
description: >-
  Hub-student workshop using AgnosticD. Provisions a hub cluster running
  Showroom and {{NUM_STUDENTS}} student SNO/compact clusters.

prerequisites:
  - name: python3
    check_command: "python3 --version"
    version_regex: "Python (\\d+\\.\\d+\\.\\d+)"
    min_version: "3.9"
    install:
      rhel9: "sudo dnf install -y python3.12"
      fedora: "sudo dnf install -y python3.12"
      macos: "brew install python@3.12"

  - name: git
    check_command: "git --version"
    install:
      rhel9: "sudo dnf install -y git"
      fedora: "sudo dnf install -y git"
      macos: "brew install git"

  - name: jq
    check_command: "jq --version"
    install:
      rhel9: "sudo dnf install -y jq"
      fedora: "sudo dnf install -y jq"
      macos: "brew install jq"

  - name: aws-cli
    check_command: "aws --version"
    install:
      rhel9: "sudo dnf install -y awscli2"
      fedora: "sudo dnf install -y awscli2"
      macos: "brew install awscli"
    # TODO: Add gcp/azure CLI entries if using those providers

  - name: agd
    check_command: "{{AGD_ROOT}}/bin/agd --version"
    install:
      fallback: "Clone AgnosticD v2: git clone https://github.com/agnosticd/agnosticd-v2 {{AGD_ROOT}}"

setup_steps:
  - name: "Clone AgnosticD v2"
    check: "test -d {{AGD_ROOT}}"
    action: "git clone https://github.com/agnosticd/agnosticd-v2 {{AGD_ROOT}}"

  - name: "Run agd setup"
    check: "test -f {{AGD_ROOT}}/.setup-complete"
    action: "cd {{AGD_ROOT}} && ./bin/agd setup"

config:
  output_file: "deploy/config.yml"
  gitignore: true
  prompts:
    - key: project_name
      prompt: "Project name"
      default: "{{PROJECT_NAME}}"

    - key: cloud_provider
      prompt: "Cloud provider"
      default: "{{CLOUD_PROVIDER}}"
      choices: ["aws", "gcp", "azure"]

    - key: cloud_region
      prompt: "Cloud region"
      default: "{{CLOUD_REGION}}"

    - key: num_students
      prompt: "Number of student clusters"
      default: "{{NUM_STUDENTS}}"

    - key: config_name_hub
      prompt: "AgnosticD hub config name"
      default: "{{CONFIG_NAME_HUB}}"

    - key: config_name_student
      prompt: "AgnosticD student config name"
      default: "{{CONFIG_NAME_STUDENT}}"

    - key: agd_root
      prompt: "AgnosticD v2 root path"
      default: "{{AGD_ROOT}}"

    - key: account
      prompt: "Account name (matches secrets filename)"
      default: "sandbox"
      required: true

validation:
  - name: "AWS credentials valid"
    command: "aws sts get-caller-identity"
    required: true
    fail_message: "AWS credentials not configured. Run: aws configure"

  - name: "AgnosticD binary found"
    command: "test -x {{AGD_ROOT}}/bin/agd"
    required: true
    fail_message: "agd binary not found at {{AGD_ROOT}}/bin/agd"

  - name: "Secrets file exists"
    command: "test -f {{AGD_ROOT}}/ansible/secrets/${account}.yml"
    required: true
    fail_message: "Secrets file not found. Create: {{AGD_ROOT}}/ansible/secrets/${account}.yml"

post_setup:
  message: |
    Setup complete! Next steps:
      1. Review deploy/config.yml
      2. Run: make check-quota   (verify cloud quotas for {{NUM_STUDENTS}} students)
      3. Run: make deploy        (provision hub + student clusters)
      4. Run: make status        (check environment state)

    After deploy, student_info.txt will contain credentials to share with students.
