#!/usr/bin/env bash
# bootstrap.sh — Interactive setup for {{PROJECT_NAME}}
# Reads onboard.yml at startup via python3 + PyYAML.
# Generated by rhel-devops-skills scaffold (type: rhdp-workload)
#
# Usage:
#   ./bootstrap.sh                    # interactive setup
#   ./bootstrap.sh --non-interactive  # use all defaults
#   ./bootstrap.sh --check-only       # run validation checks only

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MANIFEST="$SCRIPT_DIR/onboard.yml"

if [[ -t 1 ]]; then
    RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
    BLUE='\033[0;34m'; BOLD='\033[1m'; RESET='\033[0m'
else
    RED=''; GREEN=''; YELLOW=''; BLUE=''; BOLD=''; RESET=''
fi

info()    { echo -e "${BLUE}[INFO]${RESET} $*"; }
ok()      { echo -e "  ${GREEN}[OK]${RESET}      $*"; }
fail()    { echo -e "  ${RED}[FAIL]${RESET}    $*"; }

check_python() {
    if ! command -v python3 &>/dev/null; then
        echo "ERROR: python3 is required to parse onboard.yml"
        echo "Install: sudo dnf install -y python3"
        exit 1
    fi
    if ! python3 -c "import yaml" 2>/dev/null; then
        echo "ERROR: PyYAML is required to parse onboard.yml"
        echo "Install: sudo dnf install -y python3-pyyaml"
        exit 1
    fi
}

read_manifest() {
    local key="$1"
    python3 -c "
import yaml, sys
with open('$MANIFEST') as f:
    data = yaml.safe_load(f)
keys = '$key'.split('.')
val = data
for k in keys:
    if isinstance(val, dict):
        val = val.get(k, '')
    else:
        val = ''
        break
print(val if val else '')
"
}

main() {
    check_python

    if [[ ! -f "$MANIFEST" ]]; then
        echo "ERROR: onboard.yml not found in $SCRIPT_DIR"
        exit 1
    fi

    local project_name
    project_name="$(read_manifest name)"
    echo ""
    echo -e "${BOLD}=== $project_name Setup ===${RESET}"
    echo "$(read_manifest description)"
    echo ""

    info "This script will:"
    echo "  1. Verify you are logged in to an RHDP pre-provisioned OpenShift cluster"
    echo "  2. Detect pre-created users from Keycloak SSO realm"
    echo "  3. Configure your workload deployment (Field-Sourced Content or manual)"
    echo "  4. Validate readiness"
    echo ""
    info "RHDP cluster with Keycloak-managed users (userN format, no dash)"
    info "Workload deployment via Field-Sourced Content GitOps (Helm/Ansible + ArgoCD)"
    echo ""

    info "For full interactive onboarding, use the 'onboard' AI skill."
    info "Or run: make setup"
}

main "$@"
