# {{PROJECT_NAME}} — RHDP Workload Bootstrap
# Generated by rhel-devops-skills scaffold (type: rhdp-workload)

PROJECT_TYPE := rhdp-workload
WORKSHOP_LIB ?= $(HOME)/.local/share/rhel-devops-skills

DEPLOY_SCRIPT := scripts/deploy-workloads.sh
TEARDOWN_SCRIPT := scripts/teardown-workloads.sh
QUOTA_SCRIPT := scripts/check-quota.sh
BOOTSTRAP_SCRIPT := bootstrap.sh

include $(WORKSHOP_LIB)/workshop.mk
