# onboard.yml — Project onboarding manifest for {{PROJECT_NAME}}
# Generated by rhel-devops-skills scaffold (type: rhdp-workload)
# Schema: https://github.com/tosin2013/rhel-devops-skills-cli (onboard skill)

name: "{{PROJECT_NAME}}"
description: >-
  RHDP pre-provisioned cluster workload bootstrap: deploys workshop workloads
  (operators, applications, pipelines) onto an existing OpenShift cluster
  ordered from the RHDP catalog. Users are pre-created via Keycloak/RHBK.

prerequisites:
  - name: python3
    check_command: "python3 --version"
    version_regex: "Python (\\d+\\.\\d+\\.\\d+)"
    min_version: "3.9"
    install:
      rhel9: "sudo dnf install -y python3.12"
      fedora: "sudo dnf install -y python3.12"
      macos: "brew install python@3.12"

  - name: git
    check_command: "git --version"
    install:
      rhel9: "sudo dnf install -y git"
      fedora: "sudo dnf install -y git"
      macos: "brew install git"

  - name: jq
    check_command: "jq --version"
    install:
      rhel9: "sudo dnf install -y jq"
      fedora: "sudo dnf install -y jq"
      macos: "brew install jq"

  - name: oc
    check_command: "oc version --client"
    install:
      rhel9: "sudo dnf install -y openshift-clients"
      fedora: "sudo dnf install -y openshift-clients"
      macos: "brew install openshift-cli"

  - name: helm
    check_command: "helm version --short"
    install:
      rhel9: "sudo dnf install -y helm"
      fedora: "sudo dnf install -y helm"
      macos: "brew install helm"

setup_steps:
  - name: "Verify oc login to RHDP cluster"
    check: "oc whoami"
    action: "echo 'ERROR: Not logged in. Run: oc login <RHDP_CLUSTER_API_URL> --token=<TOKEN>' && exit 1"

  - name: "Verify cluster-admin access"
    check: "oc auth can-i '*' '*' --all-namespaces"
    action: "echo 'ERROR: cluster-admin access required. Log in with the admin user provided by RHDP.' && exit 1"

config:
  output_file: "deploy/config.yml"
  gitignore: true
  prompts:
    - key: project_name
      prompt: "Project name"
      default: "{{PROJECT_NAME}}"

    - key: deploy_mode
      prompt: "Deploy mode"
      default: "{{DEPLOY_MODE}}"
      choices: ["ocp_workloads", "rhel_vms", "both"]

    - key: num_users
      prompt: "Number of workshop users (auto-detected from Keycloak if 0)"
      default: "{{NUM_USERS}}"

    - key: namespace_prefix
      prompt: "User namespace prefix"
      default: "{{NAMESPACE_PREFIX}}"

    - key: include_showroom
      prompt: "Include Showroom lab guide? (y/n)"
      default: "{{INCLUDE_SHOWROOM}}"

    - key: use_field_content
      prompt: "Use Field-Sourced Content GitOps deployment? (y/n)"
      default: "{{USE_FIELD_CONTENT}}"

    - key: field_content_repo
      prompt: "Field content Git repo URL"
      default: "{{FIELD_CONTENT_REPO}}"

    - key: field_content_ref
      prompt: "Field content Git ref (branch/tag)"
      default: "{{FIELD_CONTENT_REF}}"

    - key: field_content_pattern
      prompt: "Field content deployment pattern (helm/ansible)"
      default: "{{FIELD_CONTENT_PATTERN}}"
      choices: ["helm", "ansible"]

    - key: field_content_namespace
      prompt: "ArgoCD Application target namespace"
      default: "{{FIELD_CONTENT_NAMESPACE}}"

validation:
  - name: "Logged in to OpenShift cluster"
    command: "oc whoami"
    required: true
    fail_message: "Not logged in to OpenShift. Run: oc login <RHDP_CLUSTER_API_URL>"

  - name: "Cluster-admin access"
    command: "oc auth can-i '*' '*' --all-namespaces"
    required: true
    fail_message: "cluster-admin access required. Log in as the RHDP admin user."

  - name: "Keycloak namespace exists"
    command: "oc get namespace keycloak"
    required: true
    fail_message: "keycloak namespace not found. Is this an RHDP pre-provisioned cluster with 'Create users on cluster' enabled?"

  - name: "RHBK operator running"
    command: "oc get csv -n keycloak --no-headers 2>/dev/null | grep -q Succeeded"
    required: true
    fail_message: "Red Hat Build of Keycloak operator not in Succeeded state in keycloak namespace."

  - name: "Keycloak SSO realm configured"
    command: "oc get keycloakrealmimport sso -n keycloak"
    required: true
    fail_message: "KeycloakRealmImport 'sso' not found in keycloak namespace. RHDP user provisioning may not be complete."

  - name: "Pre-created users detected"
    command: "oc get keycloakrealmimport sso -n keycloak -o jsonpath='{.spec.realm.users}' | python3 -c \"import sys,json; users=json.load(sys.stdin); sys.exit(0 if len(users)>0 else 1)\""
    required: true
    fail_message: "No users found in KeycloakRealmImport SSO realm. RHDP user provisioning may not be complete."

  - name: "oc CLI available"
    command: "oc version --client"
    required: true
    fail_message: "oc CLI not found. Install: sudo dnf install -y openshift-clients"

  - name: "OpenID identity provider configured"
    command: "oc get oauth cluster -o jsonpath='{.spec.identityProviders}' | grep -q openID"
    required: false
    fail_message: "OpenID identity provider not detected on cluster OAuth. Users may not be able to log in."

  - name: "ArgoCD / OpenShift GitOps operator available"
    command: "oc get csv -A --no-headers 2>/dev/null | grep -q openshift-gitops"
    required: false
    fail_message: "OpenShift GitOps operator not found. Required for Field-Sourced Content deployment. Install via: oc apply -f operators/openshift-gitops-sub.yaml"

post_setup:
  message: |
    Setup complete! Next steps:
      1. Review deploy/config.yml
      2. Run: make deploy        (deploy workloads to RHDP cluster)
      3. Run: make status        (check environment state)

    RHDP cluster users are pre-created via Keycloak (format: user1, user2, ...).
    Each user has a unique password stored in the KeycloakRealmImport CR.
    After deploy, student_info.txt will contain per-user access details.

    Field-Sourced Content integration:
      If use_field_content=y, workloads deploy via ArgoCD from your Git repo.
      Repo: {{FIELD_CONTENT_REPO}} (ref: {{FIELD_CONTENT_REF}})
      Pattern: {{FIELD_CONTENT_PATTERN}} | Namespace: {{FIELD_CONTENT_NAMESPACE}}
      Label resources with demo.redhat.com/userinfo for data passback.
