#!/usr/bin/env bash
# deploy-demo.sh — Provision demo cluster for {{PROJECT_NAME}}
# Generated by rhel-devops-skills scaffold (type: demo)
#
# Usage:
#   ./scripts/deploy-demo.sh             # Full deploy
#   ./scripts/deploy-demo.sh --dry-run   # Preview without provisioning
#   ./scripts/deploy-demo.sh --yes       # Skip confirmation

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_ROOT"

WORKSHOP_LIB="${WORKSHOP_LIB:-$HOME/.local/share/rhel-devops-skills}"
# shellcheck source=/dev/null
source "$WORKSHOP_LIB/workshop-common.sh"

# ─── Argument Parsing ────────────────────────────────────────────────────────

WS_DRY_RUN=false
WS_YES=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --dry-run)   WS_DRY_RUN=true; shift ;;
        --yes|-y)    WS_YES=true; shift ;;
        --confirm)   shift ;;
        *) echo "Unknown option: $1"; exit 2 ;;
    esac
done

export WS_DRY_RUN WS_YES

# ─── Load Config ─────────────────────────────────────────────────────────────

workshop_load_config

CONFIG_NAME="${WS_CFG_CONFIG_NAME:-{{CONFIG_NAME}}}"
AGD_ROOT="${WS_CFG_AGD_ROOT:-{{AGD_ROOT}}}"
CLOUD_PROVIDER="${WS_CFG_CLOUD_PROVIDER:-{{CLOUD_PROVIDER}}}"
CLOUD_REGION="${WS_CFG_CLOUD_REGION:-{{CLOUD_REGION}}}"
ACCOUNT="${WS_CFG_ACCOUNT:-sandbox}"

VARS_DIR="$AGD_ROOT/agnosticd-v2-vars"
VARS_FILE="$VARS_DIR/${CONFIG_NAME}.yaml"

# ─── Initialize ──────────────────────────────────────────────────────────────

workshop_state_lock || exit 1
trap 'workshop_state_unlock' EXIT

GUID="$(workshop_get_guid)"
if [[ -z "$GUID" ]]; then
    GUID="$(workshop_generate_guid)"
    workshop_save_state "guid" "$GUID"
    workshop_save_state "project_type" "demo"
    workshop_save_state "project_name" "{{PROJECT_NAME}}"
    workshop_save_state "cloud_provider" "$CLOUD_PROVIDER"
    workshop_save_state "cloud_region" "$CLOUD_REGION"
fi

LOGFILE="$(workshop_init_logging "$GUID")"
workshop_log INFO "Deploy started: GUID=$GUID, provider=$CLOUD_PROVIDER, region=$CLOUD_REGION"
workshop_log INFO "Config: $CONFIG_NAME"

# ─── Deploy ──────────────────────────────────────────────────────────────────

workshop_idempotency_check "Demo cluster" "cluster_status" || true

if [[ "$(workshop_get_state cluster_status)" != "deployed" ]] || [[ "$WS_DRY_RUN" == "true" ]]; then
    workshop_agd_provision "$CONFIG_NAME" "$VARS_FILE" "$GUID"

    if [[ "$WS_DRY_RUN" != "true" ]]; then
        workshop_save_state "cluster_status" "deployed"
        workshop_save_state "cluster_deployed_at" "$(date -Iseconds)"
    fi
fi

# ─── Post-Deploy ─────────────────────────────────────────────────────────────

if [[ "$WS_DRY_RUN" != "true" ]]; then
    workshop_save_state "state" "deployed"
    workshop_generate_deployment_info "{{PROJECT_NAME}}" "$GUID" "demo"

    echo ""
    workshop_log OK "Deployment complete!"
    workshop_log INFO "GUID: $GUID"
    workshop_log INFO "Deployment info: deployment_info.txt"
    workshop_log INFO "Logs: $LOGFILE"
fi
