#!/usr/bin/env bash
# teardown-demo.sh — Destroy demo cluster for {{PROJECT_NAME}}
# Generated by rhel-devops-skills scaffold (type: demo)
#
# Usage:
#   ./scripts/teardown-demo.sh             # Destroy cluster
#   ./scripts/teardown-demo.sh --dry-run   # Preview
#   ./scripts/teardown-demo.sh --yes       # Skip confirmation

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_ROOT"

WORKSHOP_LIB="${WORKSHOP_LIB:-$HOME/.local/share/rhel-devops-skills}"
# shellcheck source=/dev/null
source "$WORKSHOP_LIB/workshop-common.sh"

# ─── Argument Parsing ────────────────────────────────────────────────────────

WS_DRY_RUN=false
WS_YES=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --dry-run)   WS_DRY_RUN=true; shift ;;
        --yes|-y)    WS_YES=true; shift ;;
        --confirm)   shift ;;
        *) echo "Unknown option: $1"; exit 2 ;;
    esac
done

export WS_DRY_RUN WS_YES

# ─── Load Config ─────────────────────────────────────────────────────────────

workshop_load_config

CONFIG_NAME="${WS_CFG_CONFIG_NAME:-{{CONFIG_NAME}}}"
AGD_ROOT="${WS_CFG_AGD_ROOT:-{{AGD_ROOT}}}"
ACCOUNT="${WS_CFG_ACCOUNT:-sandbox}"

VARS_DIR="$AGD_ROOT/agnosticd-v2-vars"
VARS_FILE="$VARS_DIR/${CONFIG_NAME}.yaml"

# ─── Pre-flight ──────────────────────────────────────────────────────────────

GUID="$(workshop_get_guid)"
if [[ -z "$GUID" ]]; then
    workshop_log ERROR "No deployment state found. Nothing to destroy."
    exit 1
fi

workshop_state_lock || exit 1
trap 'workshop_state_unlock' EXIT

LOGFILE="$(workshop_init_logging "$GUID")"
workshop_log INFO "Teardown started: GUID=$GUID, config=$CONFIG_NAME"

# ─── Confirmation ────────────────────────────────────────────────────────────

if [[ "$WS_DRY_RUN" != "true" ]]; then
    echo ""
    workshop_log WARN "This will DESTROY:"
    echo "  - Demo cluster ($CONFIG_NAME)"
    echo "  - GUID: $GUID"
    echo ""

    if ! workshop_confirm "Proceed with teardown?"; then
        workshop_log INFO "Teardown cancelled."
        exit 0
    fi
fi

# ─── Destroy ─────────────────────────────────────────────────────────────────

workshop_agd_destroy "$CONFIG_NAME" "$VARS_FILE" "$GUID"

if [[ "$WS_DRY_RUN" != "true" ]]; then
    workshop_save_state "state" "destroyed"
    workshop_save_state "cluster_status" "destroyed"
    workshop_save_state "destroyed_at" "$(date -Iseconds)"

    echo ""
    workshop_log OK "Teardown complete (GUID: $GUID)"
    workshop_log INFO "Logs: $LOGFILE"
fi
