#!/usr/bin/env bash
# check-quota.sh — Cloud provider quota pre-flight for {{PROJECT_NAME}}
# Generated by rhel-devops-skills scaffold (type: hub-student)
#
# Usage:
#   ./scripts/check-quota.sh               # Check quotas (read-only)
#   ./scripts/check-quota.sh --increase    # Check + request increases if needed
#   ./scripts/check-quota.sh --status      # Show current quota usage only

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_ROOT"

# Source shared library (includes quota-check.sh)
WORKSHOP_LIB="${WORKSHOP_LIB:-$HOME/.local/share/rhel-devops-skills}"
if [[ -f "$WORKSHOP_LIB/quota-check.sh" ]]; then
    # shellcheck source=/dev/null
    source "$WORKSHOP_LIB/quota-check.sh"
else
    echo "ERROR: Quota check library not found at $WORKSHOP_LIB/quota-check.sh"
    echo "Install with: ./install.sh scaffold --type hub-student"
    exit 1
fi

# Load project config
if [[ -f deploy/config.yml ]]; then
    # shellcheck source=/dev/null
    source "$WORKSHOP_LIB/workshop-common.sh"
    workshop_load_config
fi

# Run quota check with project-specific parameters
quota_check \
    --type "hub-student" \
    --provider "${WS_CFG_CLOUD_PROVIDER:-{{CLOUD_PROVIDER}}}" \
    --region "${WS_CFG_CLOUD_REGION:-{{CLOUD_REGION}}}" \
    --num-students "${WS_CFG_NUM_STUDENTS:-{{NUM_STUDENTS}}}" \
    "$@"
