#!/usr/bin/env bash
# deploy-workshop.sh — Provision hub + student clusters for {{PROJECT_NAME}}
# Generated by rhel-devops-skills scaffold (type: hub-student)
#
# Usage:
#   ./scripts/deploy-workshop.sh                  # Full deploy (hub + students)
#   ./scripts/deploy-workshop.sh --hub-only       # Deploy hub cluster only
#   ./scripts/deploy-workshop.sh --students-only  # Deploy student clusters only
#   ./scripts/deploy-workshop.sh --dry-run        # Preview without provisioning
#   ./scripts/deploy-workshop.sh --resume         # Resume failed student deploys
#   ./scripts/deploy-workshop.sh --parallel 3     # Limit parallel student deploys

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_ROOT"

# Source shared library
WORKSHOP_LIB="${WORKSHOP_LIB:-$HOME/.local/share/rhel-devops-skills}"
# shellcheck source=/dev/null
source "$WORKSHOP_LIB/workshop-common.sh"

# ─── Argument Parsing ────────────────────────────────────────────────────────

HUB_ONLY=false
STUDENTS_ONLY=false
WS_DRY_RUN=false
WS_YES=false
RESUME=false
MAX_PARALLEL=""
ACTION="provision"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --hub-only)       HUB_ONLY=true; shift ;;
        --students-only)  STUDENTS_ONLY=true; shift ;;
        --dry-run)        WS_DRY_RUN=true; shift ;;
        --yes|-y)         WS_YES=true; shift ;;
        --resume)         RESUME=true; shift ;;
        --confirm)        shift ;;  # default behavior
        --parallel)       MAX_PARALLEL="${2:-}"; shift 2 ;;
        --action)         ACTION="${2:-provision}"; shift 2 ;;
        *) echo "Unknown option: $1"; exit 2 ;;
    esac
done

export WS_DRY_RUN WS_YES

# ─── Load Config ─────────────────────────────────────────────────────────────

workshop_load_config

CONFIG_HUB="${WS_CFG_CONFIG_NAME_HUB:-{{CONFIG_NAME_HUB}}}"
CONFIG_STUDENT="${WS_CFG_CONFIG_NAME_STUDENT:-{{CONFIG_NAME_STUDENT}}}"
NUM_STUDENTS="${WS_CFG_NUM_STUDENTS:-{{NUM_STUDENTS}}}"
AGD_ROOT="${WS_CFG_AGD_ROOT:-{{AGD_ROOT}}}"
CLOUD_PROVIDER="${WS_CFG_CLOUD_PROVIDER:-{{CLOUD_PROVIDER}}}"
CLOUD_REGION="${WS_CFG_CLOUD_REGION:-{{CLOUD_REGION}}}"
ACCOUNT="${WS_CFG_ACCOUNT:-sandbox}"

VARS_DIR="$AGD_ROOT/agnosticd-v2-vars"
HUB_VARS="$VARS_DIR/${CONFIG_HUB}.yaml"
STUDENT_VARS="$VARS_DIR/${CONFIG_STUDENT}.yaml"

# ─── Initialize ──────────────────────────────────────────────────────────────

workshop_state_lock || exit 1
trap 'workshop_state_unlock' EXIT

GUID="$(workshop_get_guid)"
if [[ -z "$GUID" ]]; then
    GUID="$(workshop_generate_guid)"
    workshop_save_state "guid" "$GUID"
    workshop_save_state "project_type" "hub-student"
    workshop_save_state "project_name" "{{PROJECT_NAME}}"
    workshop_save_state "cloud_provider" "$CLOUD_PROVIDER"
    workshop_save_state "cloud_region" "$CLOUD_REGION"
fi

LOGFILE="$(workshop_init_logging "$GUID")"
workshop_log INFO "Deploy started: GUID=$GUID, provider=$CLOUD_PROVIDER, region=$CLOUD_REGION"
workshop_log INFO "Topology: 1 hub ($CONFIG_HUB) + $NUM_STUDENTS students ($CONFIG_STUDENT)"

# ─── Deploy ──────────────────────────────────────────────────────────────────

if [[ "$RESUME" == "true" ]]; then
    workshop_log INFO "Resuming partial deployment..."
    STUDENTS_ONLY=true
fi

# Hub first (serial)
if [[ "$STUDENTS_ONLY" != "true" ]]; then
    workshop_idempotency_check "Hub cluster" "hub_status" || true

    if [[ "$(workshop_get_state hub_status)" != "deployed" ]] || [[ "$WS_DRY_RUN" == "true" ]]; then
        workshop_serial_hub "$ACTION" "$CONFIG_HUB" "$HUB_VARS"
        if [[ "$WS_DRY_RUN" != "true" ]]; then
            workshop_save_state "hub_status" "deployed"
            workshop_save_state "hub_deployed_at" "$(date -Iseconds)"
        fi
    fi
fi

# Students (parallel)
if [[ "$HUB_ONLY" != "true" ]]; then
    workshop_log INFO "Deploying $NUM_STUDENTS student cluster(s)..."

    if [[ "$RESUME" == "true" ]]; then
        readarray -t failed_students < <(workshop_resume_partial "$NUM_STUDENTS")
        if [[ ${#failed_students[@]} -eq 0 ]]; then
            workshop_log OK "No failed students to resume"
        else
            # TODO: Re-provision only failed students
            workshop_log INFO "Would resume students: ${failed_students[*]}"
        fi
    else
        workshop_parallel_students "$ACTION" "$CONFIG_STUDENT" "$STUDENT_VARS" "$NUM_STUDENTS" "${MAX_PARALLEL:-$NUM_STUDENTS}"
    fi

    if [[ "$WS_DRY_RUN" != "true" ]]; then
        workshop_save_state "students_deployed_at" "$(date -Iseconds)"
    fi
fi

# ─── Post-Deploy: Generate Info File ─────────────────────────────────────────

if [[ "$WS_DRY_RUN" != "true" ]]; then
    workshop_save_state "state" "deployed"
    workshop_generate_student_info "{{PROJECT_NAME}}" "$GUID" "$NUM_STUDENTS"

    echo ""
    workshop_log OK "Deployment complete!"
    workshop_log INFO "GUID: $GUID"
    workshop_log INFO "Student info: student_info.txt"
    workshop_log INFO "Logs: $LOGFILE"
fi
