#!/usr/bin/env bash
# teardown-workshop.sh — Destroy hub + student clusters for {{PROJECT_NAME}}
# Generated by rhel-devops-skills scaffold (type: hub-student)
#
# Destroy order: Students first (parallel), then hub last.
#
# Usage:
#   ./scripts/teardown-workshop.sh                  # Full destroy
#   ./scripts/teardown-workshop.sh --hub-only       # Destroy hub only
#   ./scripts/teardown-workshop.sh --students-only  # Destroy students only
#   ./scripts/teardown-workshop.sh --dry-run        # Preview without destroying
#   ./scripts/teardown-workshop.sh --yes            # Skip confirmation

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_ROOT"

# Source shared library
WORKSHOP_LIB="${WORKSHOP_LIB:-$HOME/.local/share/rhel-devops-skills}"
# shellcheck source=/dev/null
source "$WORKSHOP_LIB/workshop-common.sh"

# ─── Argument Parsing ────────────────────────────────────────────────────────

HUB_ONLY=false
STUDENTS_ONLY=false
WS_DRY_RUN=false
WS_YES=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --hub-only)       HUB_ONLY=true; shift ;;
        --students-only)  STUDENTS_ONLY=true; shift ;;
        --dry-run)        WS_DRY_RUN=true; shift ;;
        --yes|-y)         WS_YES=true; shift ;;
        --confirm)        shift ;;
        *) echo "Unknown option: $1"; exit 2 ;;
    esac
done

export WS_DRY_RUN WS_YES

# ─── Load Config ─────────────────────────────────────────────────────────────

workshop_load_config

CONFIG_HUB="${WS_CFG_CONFIG_NAME_HUB:-{{CONFIG_NAME_HUB}}}"
CONFIG_STUDENT="${WS_CFG_CONFIG_NAME_STUDENT:-{{CONFIG_NAME_STUDENT}}}"
NUM_STUDENTS="${WS_CFG_NUM_STUDENTS:-{{NUM_STUDENTS}}}"
AGD_ROOT="${WS_CFG_AGD_ROOT:-{{AGD_ROOT}}}"
ACCOUNT="${WS_CFG_ACCOUNT:-sandbox}"

VARS_DIR="$AGD_ROOT/agnosticd-v2-vars"
HUB_VARS="$VARS_DIR/${CONFIG_HUB}.yaml"
STUDENT_VARS="$VARS_DIR/${CONFIG_STUDENT}.yaml"

# ─── Pre-flight ──────────────────────────────────────────────────────────────

GUID="$(workshop_get_guid)"
if [[ -z "$GUID" ]]; then
    workshop_log ERROR "No deployment state found (.workshop-state missing or empty)"
    workshop_log ERROR "Nothing to destroy."
    exit 1
fi

workshop_state_lock || exit 1
trap 'workshop_state_unlock' EXIT

LOGFILE="$(workshop_init_logging "$GUID")"
workshop_log INFO "Teardown started: GUID=$GUID"
workshop_log INFO "Topology: 1 hub ($CONFIG_HUB) + $NUM_STUDENTS students ($CONFIG_STUDENT)"

# ─── Confirmation ────────────────────────────────────────────────────────────

if [[ "$WS_DRY_RUN" != "true" ]]; then
    echo ""
    workshop_log WARN "This will DESTROY the following:"
    if [[ "$HUB_ONLY" != "true" ]]; then
        echo "  - $NUM_STUDENTS student cluster(s) ($CONFIG_STUDENT)"
    fi
    if [[ "$STUDENTS_ONLY" != "true" ]]; then
        echo "  - 1 hub cluster ($CONFIG_HUB)"
    fi
    echo "  - GUID: $GUID"
    echo ""

    if ! workshop_confirm "Proceed with teardown?"; then
        workshop_log INFO "Teardown cancelled."
        exit 0
    fi
fi

# ─── Destroy ─────────────────────────────────────────────────────────────────

# Students first (parallel)
if [[ "$HUB_ONLY" != "true" ]]; then
    workshop_log INFO "Destroying $NUM_STUDENTS student cluster(s)..."
    workshop_parallel_students "destroy" "$CONFIG_STUDENT" "$STUDENT_VARS" "$NUM_STUDENTS" "$NUM_STUDENTS"

    if [[ "$WS_DRY_RUN" != "true" ]]; then
        for ((i=1; i<=NUM_STUDENTS; i++)); do
            workshop_save_state "student_${i}_status" "destroyed"
        done
    fi
fi

# Hub last (serial)
if [[ "$STUDENTS_ONLY" != "true" ]]; then
    workshop_log INFO "Destroying hub cluster..."
    workshop_serial_hub "destroy" "$CONFIG_HUB" "$HUB_VARS"

    if [[ "$WS_DRY_RUN" != "true" ]]; then
        workshop_save_state "hub_status" "destroyed"
    fi
fi

# ─── Cleanup ─────────────────────────────────────────────────────────────────

if [[ "$WS_DRY_RUN" != "true" ]]; then
    workshop_save_state "state" "destroyed"
    workshop_save_state "destroyed_at" "$(date -Iseconds)"

    echo ""
    workshop_log OK "Teardown complete (GUID: $GUID)"
    workshop_log INFO "Logs: $LOGFILE"
    workshop_log INFO "State file retained for reference. Remove with: rm .workshop-state"
fi
