#!/usr/bin/env bash
# check-quota.sh — Cluster resource pre-flight for {{PROJECT_NAME}}
# Generated by rhel-devops-skills scaffold (type: rhdp-workload)
#
# Since the cluster is pre-provisioned by RHDP, this checks on-cluster
# resource availability rather than cloud provider quotas.
#
# Usage:
#   ./scripts/check-quota.sh               # Check cluster resources (read-only)
#   ./scripts/check-quota.sh --status      # Show current resource usage only

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_ROOT"

WORKSHOP_LIB="${WORKSHOP_LIB:-$HOME/.local/share/rhel-devops-skills}"
if [[ -f "$WORKSHOP_LIB/workshop-common.sh" ]]; then
    # shellcheck source=/dev/null
    source "$WORKSHOP_LIB/workshop-common.sh"
fi

if [[ -f deploy/config.yml ]]; then
    workshop_load_config
fi

NUM_USERS="${WS_CFG_NUM_USERS:-{{NUM_USERS}}}"

# ─── Cluster Resource Checks ────────────────────────────────────────────────

echo ""
echo "=== RHDP Cluster Resource Check ==="
echo ""

if ! oc whoami &>/dev/null; then
    echo "ERROR: Not logged in to OpenShift cluster"
    echo "Run: oc login <RHDP_CLUSTER_API_URL>"
    exit 1
fi

echo "Cluster: $(oc whoami --show-server 2>/dev/null)"
echo "User:    $(oc whoami 2>/dev/null)"
echo ""

echo "--- Node Capacity ---"
oc get nodes -o custom-columns=\
'NAME:.metadata.name,STATUS:.status.conditions[-1].type,CPU:.status.capacity.cpu,MEMORY:.status.capacity.memory,ROLES:.metadata.labels.node-role\.kubernetes\.io/worker' \
    --no-headers 2>/dev/null || echo "  Unable to query node capacity"
echo ""

WORKER_COUNT="$(oc get nodes -l node-role.kubernetes.io/worker --no-headers 2>/dev/null | wc -l)"
echo "Workers: $WORKER_COUNT"
echo "Users:   $NUM_USERS"
echo ""

if (( WORKER_COUNT < 3 )); then
    echo "WARNING: Fewer than 3 worker nodes. ODF/NooBaa and other storage-dependent"
    echo "         workloads require at least 3 workers."
fi

echo "--- Keycloak Status ---"
if oc get namespace keycloak &>/dev/null 2>&1; then
    echo "  Keycloak namespace: exists"
    KC_PODS="$(oc get pods -n keycloak --no-headers 2>/dev/null | grep -c Running || echo 0)"
    echo "  Running pods: $KC_PODS"
else
    echo "  Keycloak namespace: NOT FOUND"
fi

echo ""
echo "=== Resource check complete ==="
