#!/usr/bin/env bash
# deploy-workloads.sh — Deploy workloads to RHDP pre-provisioned cluster for {{PROJECT_NAME}}
# Generated by rhel-devops-skills scaffold (type: rhdp-workload)
#
# The cluster is already provisioned by RHDP. This script:
#   1. Detects pre-created users from the Keycloak SSO realm
#   2. Creates per-user namespaces and RBAC
#   3. Deploys workshop workloads (operators, apps, pipelines)
#
# Usage:
#   ./scripts/deploy-workloads.sh                # Full deploy (namespaces + workloads)
#   ./scripts/deploy-workloads.sh --users-only   # Create user namespaces only
#   ./scripts/deploy-workloads.sh --dry-run      # Preview without deploying
#   ./scripts/deploy-workloads.sh --yes          # Skip confirmation
#   ./scripts/deploy-workloads.sh --parallel 5   # Limit parallel namespace creation

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_ROOT"

WORKSHOP_LIB="${WORKSHOP_LIB:-$HOME/.local/share/rhel-devops-skills}"
# shellcheck source=/dev/null
source "$WORKSHOP_LIB/workshop-common.sh"

# ─── Argument Parsing ────────────────────────────────────────────────────────

USERS_ONLY=false
WS_DRY_RUN=false
WS_YES=false
MAX_PARALLEL=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --users-only)    USERS_ONLY=true; shift ;;
        --dry-run)       WS_DRY_RUN=true; shift ;;
        --yes|-y)        WS_YES=true; shift ;;
        --confirm)       shift ;;
        --parallel)      MAX_PARALLEL="${2:-}"; shift 2 ;;
        *) echo "Unknown option: $1"; exit 2 ;;
    esac
done

export WS_DRY_RUN WS_YES

# ─── Load Config ─────────────────────────────────────────────────────────────

workshop_load_config

DEPLOY_MODE="${WS_CFG_DEPLOY_MODE:-{{DEPLOY_MODE}}}"
NUM_USERS="${WS_CFG_NUM_USERS:-{{NUM_USERS}}}"
NAMESPACE_PREFIX="${WS_CFG_NAMESPACE_PREFIX:-{{NAMESPACE_PREFIX}}}"

# ─── Initialize ──────────────────────────────────────────────────────────────

workshop_state_lock || exit 1
trap 'workshop_state_unlock' EXIT

GUID="$(workshop_get_guid)"
if [[ -z "$GUID" ]]; then
    GUID="$(workshop_generate_guid)"
    workshop_save_state "guid" "$GUID"
    workshop_save_state "project_type" "rhdp-workload"
    workshop_save_state "project_name" "{{PROJECT_NAME}}"
    workshop_save_state "deploy_mode" "$DEPLOY_MODE"
fi

LOGFILE="$(workshop_init_logging "$GUID")"
workshop_log INFO "Deploy started: GUID=$GUID, mode=$DEPLOY_MODE"
workshop_log INFO "Topology: rhdp-workload (pre-provisioned cluster)"

# ─── Detect RHDP Users ──────────────────────────────────────────────────────

workshop_log INFO "Detecting pre-created users from Keycloak SSO realm..."

if workshop_rhdp_detect_keycloak; then
    workshop_log OK "RHDP Keycloak detected in 'keycloak' namespace"
else
    workshop_log ERROR "RHDP Keycloak not found. Is this an RHDP pre-provisioned cluster?"
    exit 1
fi

DETECTED_USERS="$(workshop_rhdp_detect_users)"
DETECTED_COUNT="$(echo "$DETECTED_USERS" | wc -w)"

if [[ "$NUM_USERS" == "0" || -z "$NUM_USERS" ]]; then
    NUM_USERS="$DETECTED_COUNT"
    workshop_log INFO "Auto-detected $NUM_USERS users from Keycloak realm"
else
    workshop_log INFO "Config specifies $NUM_USERS users ($DETECTED_COUNT detected in Keycloak)"
    if (( NUM_USERS > DETECTED_COUNT )); then
        workshop_log WARN "Requested $NUM_USERS users but only $DETECTED_COUNT exist in Keycloak"
        NUM_USERS="$DETECTED_COUNT"
    fi
fi

workshop_save_state "num_users" "$NUM_USERS"

workshop_log INFO "Resolving per-user passwords from KeycloakRealmImport..."
workshop_rhdp_resolve_passwords "$NUM_USERS"

# ─── Verify Identity Provider ───────────────────────────────────────────────

workshop_rhdp_verify_idp

# ─── Create User Namespaces ─────────────────────────────────────────────────

workshop_log INFO "Creating $NUM_USERS user namespace(s) with prefix '$NAMESPACE_PREFIX'..."

create_user_namespace() {
    local idx="$1"
    local ns="${NAMESPACE_PREFIX}${idx}"
    local user="user${idx}"

    if [[ "$WS_DRY_RUN" == "true" ]]; then
        workshop_log INFO "[DRY-RUN] Would create namespace $ns for $user"
        return 0
    fi

    if oc get namespace "$ns" &>/dev/null 2>&1; then
        workshop_log INFO "Namespace $ns already exists, skipping creation"
    else
        oc create namespace "$ns"
        workshop_log INFO "Created namespace: $ns"
    fi

    if ! oc get rolebinding "${user}-edit" -n "$ns" &>/dev/null 2>&1; then
        oc create rolebinding "${user}-edit" \
            --clusterrole=edit \
            --user="$user" \
            -n "$ns"
        workshop_log INFO "Granted edit role to $user in $ns"
    fi

    workshop_save_state "user_${idx}_namespace" "$ns"
    workshop_save_state "user_${idx}_username" "$user"
    workshop_save_state "user_${idx}_status" "ready"
}

for ((i=1; i<=NUM_USERS; i++)); do
    create_user_namespace "$i"
done

# ─── Deploy Workloads ───────────────────────────────────────────────────────

if [[ "$USERS_ONLY" != "true" ]]; then
    workshop_log INFO "Deploying workshop workloads (mode: $DEPLOY_MODE)..."

    USE_FIELD_CONTENT="${WS_CFG_USE_FIELD_CONTENT:-{{USE_FIELD_CONTENT}}}"
    FIELD_CONTENT_REPO="${WS_CFG_FIELD_CONTENT_REPO:-{{FIELD_CONTENT_REPO}}}"
    FIELD_CONTENT_REF="${WS_CFG_FIELD_CONTENT_REF:-{{FIELD_CONTENT_REF}}}"
    FIELD_CONTENT_PATTERN="${WS_CFG_FIELD_CONTENT_PATTERN:-{{FIELD_CONTENT_PATTERN}}}"
    FIELD_CONTENT_NS="${WS_CFG_FIELD_CONTENT_NAMESPACE:-{{FIELD_CONTENT_NAMESPACE}}}"

    if [[ "$USE_FIELD_CONTENT" =~ ^[Yy] ]] && [[ -n "$FIELD_CONTENT_REPO" ]]; then
        # ── Field-Sourced Content GitOps Deployment ──────────────────────
        workshop_log INFO "Deploying via Field-Sourced Content (pattern: $FIELD_CONTENT_PATTERN)"
        workshop_log INFO "Repo: $FIELD_CONTENT_REPO (ref: $FIELD_CONTENT_REF)"

        CLUSTER_DOMAIN="$(oc get ingresses.config/cluster -o jsonpath='{.spec.domain}' 2>/dev/null)"
        CLUSTER_API="$(oc whoami --show-server 2>/dev/null)"

        if [[ "$WS_DRY_RUN" == "true" ]]; then
            workshop_log INFO "[DRY-RUN] Would create namespace $FIELD_CONTENT_NS"
            workshop_log INFO "[DRY-RUN] Would create ArgoCD Application field-content-{{PROJECT_NAME}}"
        else
            if ! oc get namespace "$FIELD_CONTENT_NS" &>/dev/null 2>&1; then
                oc create namespace "$FIELD_CONTENT_NS"
                workshop_log INFO "Created namespace: $FIELD_CONTENT_NS"
            fi

            oc apply -f - <<ARGOEOF
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "field-content-{{PROJECT_NAME}}"
  namespace: openshift-gitops
  labels:
    demo.redhat.com/application: "{{PROJECT_NAME}}"
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  destination:
    namespace: "$FIELD_CONTENT_NS"
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: "$FIELD_CONTENT_REPO"
    targetRevision: "$FIELD_CONTENT_REF"
    $(if [[ "$FIELD_CONTENT_PATTERN" == "helm" ]]; then
      echo "helm:"
      echo "      values: |"
      echo "        global:"
      echo "          clusterDomain: \"$CLUSTER_DOMAIN\""
      echo "          clusterApiUrl: \"$CLUSTER_API\""
      echo "          namespace: \"$FIELD_CONTENT_NS\""
      echo "          numUsers: $NUM_USERS"
    else
      echo "directory:"
      echo "      recurse: true"
    fi)
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
ARGOEOF

            workshop_log OK "ArgoCD Application created: field-content-{{PROJECT_NAME}}"
            workshop_log INFO "ArgoCD will sync workloads from $FIELD_CONTENT_REPO"
            workshop_log INFO "Monitor sync: oc get application field-content-{{PROJECT_NAME}} -n openshift-gitops"

            workshop_save_state "field_content_app" "field-content-{{PROJECT_NAME}}"
            workshop_save_state "field_content_repo" "$FIELD_CONTENT_REPO"
            workshop_save_state "field_content_namespace" "$FIELD_CONTENT_NS"
        fi
    else
        # ── Manual Workload Deployment ───────────────────────────────────
        # Add custom deployment steps here if not using Field-Sourced Content.
        # Examples:
        #   - Operator subscriptions (oc apply -f operators/)
        #   - Helm chart installations (helm install ...)
        #   - Kustomize overlays (oc apply -k overlays/production/)
        #   - Shell-based bootstrap scripts
        #
        # The deploy_mode variable controls what gets deployed:
        #   ocp_workloads — OpenShift operators and applications only
        #   rhel_vms      — RHEL VM provisioning only
        #   both          — Both OpenShift workloads and RHEL VMs

        workshop_log INFO "Field-Sourced Content not enabled — add custom deployment logic here"
        workshop_log INFO "Or re-run scaffold with USE_FIELD_CONTENT=y to enable GitOps deployment"
    fi

    if [[ "$WS_DRY_RUN" != "true" ]]; then
        workshop_save_state "workloads_status" "deployed"
        workshop_save_state "workloads_deployed_at" "$(date -Iseconds)"
    fi
fi

# ─── Post-Deploy ─────────────────────────────────────────────────────────────

if [[ "$WS_DRY_RUN" != "true" ]]; then
    workshop_save_state "state" "deployed"
    workshop_save_state "users_created_at" "$(date -Iseconds)"

    CLUSTER_CONSOLE="$(oc whoami --show-console 2>/dev/null || echo 'unknown')"
    workshop_save_state "cluster_console_url" "$CLUSTER_CONSOLE"

    workshop_generate_student_info "{{PROJECT_NAME}}" "$GUID" "$NUM_USERS"

    echo ""
    workshop_log OK "Deployment complete!"
    workshop_log INFO "GUID: $GUID"
    workshop_log INFO "Console: $CLUSTER_CONSOLE"
    workshop_log INFO "Users: $NUM_USERS (format: user1 .. user${NUM_USERS}, no dash)"
    workshop_log INFO "Namespaces: ${NAMESPACE_PREFIX}1 .. ${NAMESPACE_PREFIX}${NUM_USERS}"
    workshop_log INFO "Student info: student_info.txt"
    workshop_log INFO "Logs: $LOGFILE"
fi
