#!/usr/bin/env bash
# teardown-workloads.sh — Remove workshop workloads from RHDP cluster for {{PROJECT_NAME}}
# Generated by rhel-devops-skills scaffold (type: rhdp-workload)
#
# The RHDP cluster itself is NOT destroyed (it is managed by the RHDP catalog).
# This script only removes workshop-deployed resources:
#   1. Workshop workloads (operators, apps, pipelines)
#   2. Per-user namespaces and RBAC
#
# Usage:
#   ./scripts/teardown-workloads.sh                # Full teardown (workloads + namespaces)
#   ./scripts/teardown-workloads.sh --users-only   # Delete user namespaces only
#   ./scripts/teardown-workloads.sh --dry-run      # Preview without destroying
#   ./scripts/teardown-workloads.sh --yes          # Skip confirmation

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_ROOT"

WORKSHOP_LIB="${WORKSHOP_LIB:-$HOME/.local/share/rhel-devops-skills}"
# shellcheck source=/dev/null
source "$WORKSHOP_LIB/workshop-common.sh"

# ─── Argument Parsing ────────────────────────────────────────────────────────

USERS_ONLY=false
WS_DRY_RUN=false
WS_YES=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --users-only)    USERS_ONLY=true; shift ;;
        --dry-run)       WS_DRY_RUN=true; shift ;;
        --yes|-y)        WS_YES=true; shift ;;
        --confirm)       shift ;;
        *) echo "Unknown option: $1"; exit 2 ;;
    esac
done

export WS_DRY_RUN WS_YES

# ─── Load Config ─────────────────────────────────────────────────────────────

workshop_load_config

NUM_USERS="${WS_CFG_NUM_USERS:-{{NUM_USERS}}}"
NAMESPACE_PREFIX="${WS_CFG_NAMESPACE_PREFIX:-{{NAMESPACE_PREFIX}}}"

# ─── Pre-flight ──────────────────────────────────────────────────────────────

GUID="$(workshop_get_guid)"
if [[ -z "$GUID" ]]; then
    workshop_log ERROR "No deployment state found (.workshop-state missing or empty)"
    workshop_log ERROR "Nothing to tear down."
    exit 1
fi

workshop_state_lock || exit 1
trap 'workshop_state_unlock' EXIT

LOGFILE="$(workshop_init_logging "$GUID")"
workshop_log INFO "Teardown started: GUID=$GUID"
workshop_log INFO "Topology: rhdp-workload, $NUM_USERS users, prefix=$NAMESPACE_PREFIX"

# ─── Confirmation ────────────────────────────────────────────────────────────

if [[ "$WS_DRY_RUN" != "true" ]]; then
    echo ""
    workshop_log WARN "This will REMOVE the following from the RHDP cluster:"
    echo "  - $NUM_USERS user namespace(s) (${NAMESPACE_PREFIX}1 .. ${NAMESPACE_PREFIX}${NUM_USERS})"
    if [[ "$USERS_ONLY" != "true" ]]; then
        echo "  - Workshop workloads (operators, applications)"
    fi
    echo "  - GUID: $GUID"
    echo ""
    workshop_log INFO "NOTE: The RHDP cluster itself will NOT be destroyed."
    echo ""

    if ! workshop_confirm "Proceed with teardown?"; then
        workshop_log INFO "Teardown cancelled."
        exit 0
    fi
fi

# ─── Remove Workshop Workloads ──────────────────────────────────────────────

if [[ "$USERS_ONLY" != "true" ]]; then
    workshop_log INFO "Removing workshop workloads..."

    FIELD_CONTENT_APP="$(workshop_get_state field_content_app)"
    FIELD_CONTENT_NS="$(workshop_get_state field_content_namespace)"

    if [[ -n "$FIELD_CONTENT_APP" ]]; then
        # ── Field-Sourced Content ArgoCD Cleanup ─────────────────────────
        workshop_log INFO "Removing ArgoCD Application: $FIELD_CONTENT_APP"

        if [[ "$WS_DRY_RUN" == "true" ]]; then
            workshop_log INFO "[DRY-RUN] Would delete ArgoCD Application $FIELD_CONTENT_APP"
            workshop_log INFO "[DRY-RUN] Would delete namespace $FIELD_CONTENT_NS"
        else
            if oc get application "$FIELD_CONTENT_APP" -n openshift-gitops &>/dev/null 2>&1; then
                oc delete application "$FIELD_CONTENT_APP" -n openshift-gitops --wait=false
                workshop_log INFO "Deleted ArgoCD Application: $FIELD_CONTENT_APP"
                workshop_log INFO "ArgoCD will prune managed resources automatically"
            else
                workshop_log INFO "ArgoCD Application $FIELD_CONTENT_APP not found, skipping"
            fi

            if [[ -n "$FIELD_CONTENT_NS" ]] && oc get namespace "$FIELD_CONTENT_NS" &>/dev/null 2>&1; then
                oc delete namespace "$FIELD_CONTENT_NS" --wait=false
                workshop_log INFO "Deleted field content namespace: $FIELD_CONTENT_NS"
            fi
        fi
    else
        # ── Manual Workload Removal ──────────────────────────────────────
        # Add custom workload removal steps here (reverse of deploy).
        # Examples:
        #   - Helm uninstall
        #   - Remove operator subscriptions and CSVs
        #   - Delete Kustomize-applied resources
        workshop_log INFO "No Field-Sourced Content application found in state"
        workshop_log INFO "Add custom removal logic if workloads were deployed manually"
    fi

    if [[ "$WS_DRY_RUN" != "true" ]]; then
        workshop_save_state "workloads_status" "removed"
    fi
fi

# ─── Delete User Namespaces ─────────────────────────────────────────────────

workshop_log INFO "Deleting $NUM_USERS user namespace(s)..."

for ((i=1; i<=NUM_USERS; i++)); do
    local_ns="${NAMESPACE_PREFIX}${i}"

    if [[ "$WS_DRY_RUN" == "true" ]]; then
        workshop_log INFO "[DRY-RUN] Would delete namespace $local_ns"
        continue
    fi

    if oc get namespace "$local_ns" &>/dev/null 2>&1; then
        oc delete namespace "$local_ns" --wait=false
        workshop_log INFO "Deleted namespace: $local_ns"
    else
        workshop_log INFO "Namespace $local_ns not found, skipping"
    fi

    workshop_save_state "user_${i}_status" "destroyed"
done

# ─── Cleanup ─────────────────────────────────────────────────────────────────

if [[ "$WS_DRY_RUN" != "true" ]]; then
    workshop_save_state "state" "torn-down"
    workshop_save_state "torn_down_at" "$(date -Iseconds)"

    echo ""
    workshop_log OK "Teardown complete (GUID: $GUID)"
    workshop_log INFO "The RHDP cluster is still running — retire it via the RHDP catalog."
    workshop_log INFO "Logs: $LOGFILE"
    workshop_log INFO "State file retained for reference. Remove with: rm .workshop-state"
fi
