# {{PROJECT_NAME}} — Demo Environment
# Generated by rhel-devops-skills scaffold (type: demo)

PROJECT_TYPE := demo
WORKSHOP_LIB ?= $(HOME)/.local/share/rhel-devops-skills

DEPLOY_SCRIPT := scripts/deploy-demo.sh
TEARDOWN_SCRIPT := scripts/teardown-demo.sh
QUOTA_SCRIPT := scripts/check-quota.sh
BOOTSTRAP_SCRIPT := bootstrap.sh

include $(WORKSHOP_LIB)/workshop.mk
