# {{PROJECT_NAME}} — Shared-Cluster Workshop
# Generated by rhel-devops-skills scaffold (type: shared-cluster)

PROJECT_TYPE := shared-cluster
WORKSHOP_LIB ?= $(HOME)/.local/share/rhel-devops-skills

DEPLOY_SCRIPT := scripts/deploy-shared.sh
TEARDOWN_SCRIPT := scripts/teardown-shared.sh
QUOTA_SCRIPT := scripts/check-quota.sh
BOOTSTRAP_SCRIPT := bootstrap.sh

include $(WORKSHOP_LIB)/workshop.mk
