# onboard.yml — Project onboarding manifest for {{PROJECT_NAME}}
# Generated by rhel-devops-skills scaffold (type: shared-cluster)
# Schema: https://github.com/tosin2013/rhel-devops-skills-cli (onboard skill)

name: "{{PROJECT_NAME}}"
description: >-
  Shared-cluster multi-user workshop: single OpenShift cluster with
  {{NUM_USERS}} user namespaces provisioned via AgnosticD.

prerequisites:
  - name: python3
    check_command: "python3 --version"
    version_regex: "Python (\\d+\\.\\d+\\.\\d+)"
    min_version: "3.9"
    install:
      rhel9: "sudo dnf install -y python3.12"
      fedora: "sudo dnf install -y python3.12"
      macos: "brew install python@3.12"

  - name: git
    check_command: "git --version"
    install:
      rhel9: "sudo dnf install -y git"
      fedora: "sudo dnf install -y git"
      macos: "brew install git"

  - name: jq
    check_command: "jq --version"
    install:
      rhel9: "sudo dnf install -y jq"
      fedora: "sudo dnf install -y jq"
      macos: "brew install jq"

  - name: oc
    check_command: "oc version --client"
    install:
      rhel9: "sudo dnf install -y openshift-clients"
      fedora: "sudo dnf install -y openshift-clients"
      macos: "brew install openshift-cli"

  - name: aws-cli
    check_command: "aws --version"
    install:
      rhel9: "sudo dnf install -y awscli2"
      fedora: "sudo dnf install -y awscli2"
      macos: "brew install awscli"

  - name: agd
    check_command: "{{AGD_ROOT}}/bin/agd --version"
    install:
      fallback: "Clone AgnosticD v2: git clone https://github.com/agnosticd/agnosticd-v2 {{AGD_ROOT}}"

setup_steps:
  - name: "Clone AgnosticD v2"
    check: "test -d {{AGD_ROOT}}"
    action: "git clone https://github.com/agnosticd/agnosticd-v2 {{AGD_ROOT}}"

  - name: "Run agd setup"
    check: "test -f {{AGD_ROOT}}/.setup-complete"
    action: "cd {{AGD_ROOT}} && ./bin/agd setup"

config:
  output_file: "deploy/config.yml"
  gitignore: true
  prompts:
    - key: project_name
      prompt: "Project name"
      default: "{{PROJECT_NAME}}"

    - key: cloud_provider
      prompt: "Cloud provider"
      default: "{{CLOUD_PROVIDER}}"
      choices: ["aws", "gcp", "azure"]

    - key: cloud_region
      prompt: "Cloud region"
      default: "{{CLOUD_REGION}}"

    - key: config_name
      prompt: "AgnosticD config name"
      default: "{{CONFIG_NAME}}"

    - key: num_users
      prompt: "Number of workshop users"
      default: "{{NUM_USERS}}"

    - key: namespace_prefix
      prompt: "User namespace prefix"
      default: "{{NAMESPACE_PREFIX}}"

    - key: agd_root
      prompt: "AgnosticD v2 root path"
      default: "{{AGD_ROOT}}"

    - key: account
      prompt: "Account name (matches secrets filename)"
      default: "sandbox"
      required: true

    - key: include_showroom
      prompt: "Include Showroom lab guide? (y/n)"
      default: "{{INCLUDE_SHOWROOM}}"

validation:
  - name: "AWS credentials valid"
    command: "aws sts get-caller-identity"
    required: true
    fail_message: "AWS credentials not configured. Run: aws configure"

  - name: "AgnosticD binary found"
    command: "test -x {{AGD_ROOT}}/bin/agd"
    required: true
    fail_message: "agd binary not found at {{AGD_ROOT}}/bin/agd"

  - name: "oc CLI available"
    command: "oc version --client"
    required: true
    fail_message: "oc CLI not found. Install: sudo dnf install -y openshift-clients"

  - name: "Secrets file exists"
    command: "test -f {{AGD_ROOT}}/ansible/secrets/${account}.yml"
    required: true
    fail_message: "Secrets file not found."

post_setup:
  message: |
    Setup complete! Next steps:
      1. Review deploy/config.yml
      2. Run: make check-quota   (verify cloud quotas)
      3. Run: make deploy        (provision cluster + user namespaces)
      4. Run: make status        (check environment state)

    After deploy, student_info.txt will contain per-user access details.
