# {{PROJECT_NAME}} — AgnosticD Infrastructure
# Generated by rhel-devops-skills scaffold (type: agnosticd-infra)

PROJECT_TYPE := agnosticd-infra
WORKSHOP_LIB ?= $(HOME)/.local/share/rhel-devops-skills

DEPLOY_SCRIPT := scripts/deploy.sh
TEARDOWN_SCRIPT := scripts/teardown.sh
QUOTA_SCRIPT := scripts/check-quota.sh
BOOTSTRAP_SCRIPT := bootstrap.sh

include $(WORKSHOP_LIB)/workshop.mk
