#!/usr/bin/env bash
# deploy-shared.sh — Provision shared cluster + user namespaces for {{PROJECT_NAME}}
# Generated by rhel-devops-skills scaffold (type: shared-cluster)
#
# Usage:
#   ./scripts/deploy-shared.sh                # Full deploy (cluster + users)
#   ./scripts/deploy-shared.sh --users-only   # Create user namespaces only (cluster already exists)
#   ./scripts/deploy-shared.sh --dry-run      # Preview without provisioning
#   ./scripts/deploy-shared.sh --yes          # Skip confirmation
#   ./scripts/deploy-shared.sh --parallel 5   # Limit parallel namespace creation

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_ROOT"

WORKSHOP_LIB="${WORKSHOP_LIB:-$HOME/.local/share/rhel-devops-skills}"
# shellcheck source=/dev/null
source "$WORKSHOP_LIB/workshop-common.sh"

# ─── Argument Parsing ────────────────────────────────────────────────────────

USERS_ONLY=false
WS_DRY_RUN=false
WS_YES=false
MAX_PARALLEL=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --users-only)    USERS_ONLY=true; shift ;;
        --dry-run)       WS_DRY_RUN=true; shift ;;
        --yes|-y)        WS_YES=true; shift ;;
        --confirm)       shift ;;
        --parallel)      MAX_PARALLEL="${2:-}"; shift 2 ;;
        *) echo "Unknown option: $1"; exit 2 ;;
    esac
done

export WS_DRY_RUN WS_YES

# ─── Load Config ─────────────────────────────────────────────────────────────

workshop_load_config

CONFIG_NAME="${WS_CFG_CONFIG_NAME:-{{CONFIG_NAME}}}"
NUM_USERS="${WS_CFG_NUM_USERS:-{{NUM_USERS}}}"
NAMESPACE_PREFIX="${WS_CFG_NAMESPACE_PREFIX:-{{NAMESPACE_PREFIX}}}"
AGD_ROOT="${WS_CFG_AGD_ROOT:-{{AGD_ROOT}}}"
CLOUD_PROVIDER="${WS_CFG_CLOUD_PROVIDER:-{{CLOUD_PROVIDER}}}"
CLOUD_REGION="${WS_CFG_CLOUD_REGION:-{{CLOUD_REGION}}}"
ACCOUNT="${WS_CFG_ACCOUNT:-sandbox}"

VARS_DIR="$AGD_ROOT/agnosticd-v2-vars"
VARS_FILE="$VARS_DIR/${CONFIG_NAME}.yaml"

# ─── Initialize ──────────────────────────────────────────────────────────────

workshop_state_lock || exit 1
trap 'workshop_state_unlock' EXIT

GUID="$(workshop_get_guid)"
if [[ -z "$GUID" ]]; then
    GUID="$(workshop_generate_guid)"
    workshop_save_state "guid" "$GUID"
    workshop_save_state "project_type" "shared-cluster"
    workshop_save_state "project_name" "{{PROJECT_NAME}}"
    workshop_save_state "cloud_provider" "$CLOUD_PROVIDER"
    workshop_save_state "cloud_region" "$CLOUD_REGION"
    workshop_save_state "num_users" "$NUM_USERS"
    workshop_save_state "namespace_prefix" "$NAMESPACE_PREFIX"
fi

LOGFILE="$(workshop_init_logging "$GUID")"
workshop_log INFO "Deploy started: GUID=$GUID, provider=$CLOUD_PROVIDER, region=$CLOUD_REGION"
workshop_log INFO "Topology: shared-cluster, $NUM_USERS users, prefix=$NAMESPACE_PREFIX"

# ─── Provision Cluster ───────────────────────────────────────────────────────

if [[ "$USERS_ONLY" != "true" ]]; then
    workshop_idempotency_check "Shared cluster" "cluster_status" || true

    if [[ "$(workshop_get_state cluster_status)" != "deployed" ]] || [[ "$WS_DRY_RUN" == "true" ]]; then
        workshop_agd_provision "$CONFIG_NAME" "$VARS_FILE" "$GUID"

        if [[ "$WS_DRY_RUN" != "true" ]]; then
            workshop_save_state "cluster_status" "deployed"
            workshop_save_state "cluster_deployed_at" "$(date -Iseconds)"
        fi
    fi
fi

# ─── Create User Namespaces ─────────────────────────────────────────────────

workshop_log INFO "Creating $NUM_USERS user namespace(s) with prefix '$NAMESPACE_PREFIX'..."

create_user_namespace() {
    local idx="$1"
    local ns="${NAMESPACE_PREFIX}-${idx}"
    local user="user-${idx}"

    if [[ "$WS_DRY_RUN" == "true" ]]; then
        workshop_log INFO "[DRY-RUN] Would create namespace $ns for $user"
        return 0
    fi

    if oc get namespace "$ns" &>/dev/null 2>&1; then
        workshop_log INFO "Namespace $ns already exists, skipping creation"
    else
        oc create namespace "$ns"
        workshop_log INFO "Created namespace: $ns"
    fi

    if ! oc get rolebinding "${user}-edit" -n "$ns" &>/dev/null 2>&1; then
        oc create rolebinding "${user}-edit" \
            --clusterrole=edit \
            --user="$user" \
            -n "$ns"
        workshop_log INFO "Granted edit role to $user in $ns"
    fi

    workshop_save_state "user_${idx}_namespace" "$ns"
    workshop_save_state "user_${idx}_status" "ready"
}

for ((i=1; i<=NUM_USERS; i++)); do
    create_user_namespace "$i"
done

# ─── Post-Deploy ─────────────────────────────────────────────────────────────

if [[ "$WS_DRY_RUN" != "true" ]]; then
    workshop_save_state "state" "deployed"
    workshop_save_state "users_created_at" "$(date -Iseconds)"
    workshop_generate_student_info "{{PROJECT_NAME}}" "$GUID" "$NUM_USERS"

    echo ""
    workshop_log OK "Deployment complete!"
    workshop_log INFO "GUID: $GUID"
    workshop_log INFO "Cluster: $CONFIG_NAME (shared)"
    workshop_log INFO "Users: $NUM_USERS (namespaces: ${NAMESPACE_PREFIX}-1 .. ${NAMESPACE_PREFIX}-${NUM_USERS})"
    workshop_log INFO "Student info: student_info.txt"
    workshop_log INFO "Logs: $LOGFILE"
fi
