#!/usr/bin/env bash
# teardown-shared.sh — Destroy shared cluster + user namespaces for {{PROJECT_NAME}}
# Generated by rhel-devops-skills scaffold (type: shared-cluster)
#
# Destroy order: User namespaces first, then cluster.
#
# Usage:
#   ./scripts/teardown-shared.sh                # Full destroy (namespaces + cluster)
#   ./scripts/teardown-shared.sh --users-only   # Delete user namespaces only (keep cluster)
#   ./scripts/teardown-shared.sh --dry-run      # Preview without destroying
#   ./scripts/teardown-shared.sh --yes          # Skip confirmation

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_ROOT"

WORKSHOP_LIB="${WORKSHOP_LIB:-$HOME/.local/share/rhel-devops-skills}"
# shellcheck source=/dev/null
source "$WORKSHOP_LIB/workshop-common.sh"

# ─── Argument Parsing ────────────────────────────────────────────────────────

USERS_ONLY=false
WS_DRY_RUN=false
WS_YES=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --users-only)    USERS_ONLY=true; shift ;;
        --dry-run)       WS_DRY_RUN=true; shift ;;
        --yes|-y)        WS_YES=true; shift ;;
        --confirm)       shift ;;
        *) echo "Unknown option: $1"; exit 2 ;;
    esac
done

export WS_DRY_RUN WS_YES

# ─── Load Config ─────────────────────────────────────────────────────────────

workshop_load_config

CONFIG_NAME="${WS_CFG_CONFIG_NAME:-{{CONFIG_NAME}}}"
NUM_USERS="${WS_CFG_NUM_USERS:-{{NUM_USERS}}}"
NAMESPACE_PREFIX="${WS_CFG_NAMESPACE_PREFIX:-{{NAMESPACE_PREFIX}}}"
AGD_ROOT="${WS_CFG_AGD_ROOT:-{{AGD_ROOT}}}"
ACCOUNT="${WS_CFG_ACCOUNT:-sandbox}"

VARS_DIR="$AGD_ROOT/agnosticd-v2-vars"
VARS_FILE="$VARS_DIR/${CONFIG_NAME}.yaml"

# ─── Pre-flight ──────────────────────────────────────────────────────────────

GUID="$(workshop_get_guid)"
if [[ -z "$GUID" ]]; then
    workshop_log ERROR "No deployment state found (.workshop-state missing or empty)"
    workshop_log ERROR "Nothing to destroy."
    exit 1
fi

workshop_state_lock || exit 1
trap 'workshop_state_unlock' EXIT

LOGFILE="$(workshop_init_logging "$GUID")"
workshop_log INFO "Teardown started: GUID=$GUID"
workshop_log INFO "Topology: shared-cluster, $NUM_USERS users, prefix=$NAMESPACE_PREFIX"

# ─── Confirmation ────────────────────────────────────────────────────────────

if [[ "$WS_DRY_RUN" != "true" ]]; then
    echo ""
    workshop_log WARN "This will DESTROY the following:"
    echo "  - $NUM_USERS user namespace(s) (${NAMESPACE_PREFIX}-1 .. ${NAMESPACE_PREFIX}-${NUM_USERS})"
    if [[ "$USERS_ONLY" != "true" ]]; then
        echo "  - 1 shared cluster ($CONFIG_NAME)"
    fi
    echo "  - GUID: $GUID"
    echo ""

    if ! workshop_confirm "Proceed with teardown?"; then
        workshop_log INFO "Teardown cancelled."
        exit 0
    fi
fi

# ─── Delete User Namespaces ─────────────────────────────────────────────────

workshop_log INFO "Deleting $NUM_USERS user namespace(s)..."

for ((i=1; i<=NUM_USERS; i++)); do
    local_ns="${NAMESPACE_PREFIX}-${i}"

    if [[ "$WS_DRY_RUN" == "true" ]]; then
        workshop_log INFO "[DRY-RUN] Would delete namespace $local_ns"
        continue
    fi

    if oc get namespace "$local_ns" &>/dev/null 2>&1; then
        oc delete namespace "$local_ns" --wait=false
        workshop_log INFO "Deleted namespace: $local_ns"
    else
        workshop_log INFO "Namespace $local_ns not found, skipping"
    fi

    workshop_save_state "user_${i}_status" "destroyed"
done

# ─── Destroy Cluster ─────────────────────────────────────────────────────────

if [[ "$USERS_ONLY" != "true" ]]; then
    workshop_log INFO "Destroying shared cluster ($CONFIG_NAME)..."
    workshop_serial_hub "destroy" "$CONFIG_NAME" "$VARS_FILE"

    if [[ "$WS_DRY_RUN" != "true" ]]; then
        workshop_save_state "cluster_status" "destroyed"
    fi
fi

# ─── Cleanup ─────────────────────────────────────────────────────────────────

if [[ "$WS_DRY_RUN" != "true" ]]; then
    workshop_save_state "state" "destroyed"
    workshop_save_state "destroyed_at" "$(date -Iseconds)"

    echo ""
    workshop_log OK "Teardown complete (GUID: $GUID)"
    workshop_log INFO "Logs: $LOGFILE"
    workshop_log INFO "State file retained for reference. Remove with: rm .workshop-state"
fi
