#!/usr/bin/env bash
# deploy.sh — Provision infrastructure for {{PROJECT_NAME}}
# Generated by rhel-devops-skills scaffold (type: agnosticd-infra)
#
# Usage:
#   ./scripts/deploy.sh                    # Deploy default environment
#   ./scripts/deploy.sh --env dev          # Deploy specific environment
#   ./scripts/deploy.sh --env prod         # Deploy prod environment
#   ./scripts/deploy.sh --dry-run          # Preview without provisioning
#   ./scripts/deploy.sh --resume           # Resume failed deploys
#   ./scripts/deploy.sh --action stop      # Stop infrastructure
#   ./scripts/deploy.sh --action start     # Start infrastructure

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_ROOT"

WORKSHOP_LIB="${WORKSHOP_LIB:-$HOME/.local/share/rhel-devops-skills}"
# shellcheck source=/dev/null
source "$WORKSHOP_LIB/workshop-common.sh"

# ─── Argument Parsing ────────────────────────────────────────────────────────

WS_DRY_RUN=false
WS_YES=false
RESUME=false
ENV_NAME=""
ACTION="provision"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --env)        ENV_NAME="${2:-}"; shift 2 ;;
        --dry-run)    WS_DRY_RUN=true; shift ;;
        --yes|-y)     WS_YES=true; shift ;;
        --resume)     RESUME=true; shift ;;
        --confirm)    shift ;;
        --action)     ACTION="${2:-provision}"; shift 2 ;;
        *) echo "Unknown option: $1"; exit 2 ;;
    esac
done

export WS_DRY_RUN WS_YES

# ─── Load Config ─────────────────────────────────────────────────────────────

workshop_load_config

CONFIG_NAMES="${WS_CFG_CONFIG_NAMES:-{{CONFIG_NAMES}}}"
ENVIRONMENTS="${WS_CFG_ENVIRONMENTS:-{{ENVIRONMENTS}}}"
AGD_ROOT="${WS_CFG_AGD_ROOT:-{{AGD_ROOT}}}"
CLOUD_PROVIDER="${WS_CFG_CLOUD_PROVIDER:-{{CLOUD_PROVIDER}}}"
CLOUD_REGION="${WS_CFG_CLOUD_REGION:-{{CLOUD_REGION}}}"
ACCOUNT="${WS_CFG_ACCOUNT:-sandbox}"

# Default to first environment if not specified
if [[ -z "$ENV_NAME" ]]; then
    ENV_NAME="${ENVIRONMENTS%%,*}"
fi

# Split config names into array
IFS=',' read -ra CONFIGS <<< "$CONFIG_NAMES"

# ─── Initialize ──────────────────────────────────────────────────────────────

workshop_state_lock || exit 1
trap 'workshop_state_unlock' EXIT

GUID="$(workshop_get_guid)"
if [[ -z "$GUID" ]]; then
    GUID="$(workshop_generate_guid)"
    workshop_save_state "guid" "$GUID"
    workshop_save_state "project_type" "agnosticd-infra"
    workshop_save_state "project_name" "{{PROJECT_NAME}}"
    workshop_save_state "cloud_provider" "$CLOUD_PROVIDER"
    workshop_save_state "cloud_region" "$CLOUD_REGION"
fi

workshop_save_state "active_env" "$ENV_NAME"

LOGFILE="$(workshop_init_logging "$GUID")"
workshop_log INFO "Action: $ACTION | Env: $ENV_NAME | GUID: $GUID"
workshop_log INFO "Provider: $CLOUD_PROVIDER / $CLOUD_REGION"
workshop_log INFO "Configs: ${CONFIGS[*]}"

# ─── Deploy / Stop / Start ───────────────────────────────────────────────────

for config in "${CONFIGS[@]}"; do
    config="$(echo "$config" | xargs)"  # trim whitespace
    local_vars="vars/${ENV_NAME}.yml"
    agd_vars="$AGD_ROOT/agnosticd-v2-vars/${config}.yaml"
    vars_file="${local_vars}"

    if [[ ! -f "$vars_file" ]]; then
        vars_file="$agd_vars"
    fi

    state_key="config_${config}_${ENV_NAME}_status"

    if [[ "$RESUME" == "true" ]]; then
        local current_status
        current_status="$(workshop_get_state "$state_key")"
        if [[ "$current_status" == "deployed" || "$current_status" == "running" ]]; then
            workshop_log INFO "Skipping $config ($ENV_NAME) — already $current_status"
            continue
        fi
    fi

    case "$ACTION" in
        provision)
            workshop_idempotency_check "$config ($ENV_NAME)" "$state_key" || continue
            workshop_agd_provision "$config" "$vars_file" "$GUID"
            [[ "$WS_DRY_RUN" != "true" ]] && workshop_save_state "$state_key" "deployed"
            ;;
        destroy)
            workshop_agd_destroy "$config" "$vars_file" "$GUID"
            [[ "$WS_DRY_RUN" != "true" ]] && workshop_save_state "$state_key" "destroyed"
            ;;
        stop)
            workshop_agd_stop "$config" "$vars_file" "$GUID"
            [[ "$WS_DRY_RUN" != "true" ]] && workshop_save_state "$state_key" "stopped"
            ;;
        start)
            workshop_agd_start "$config" "$vars_file" "$GUID"
            [[ "$WS_DRY_RUN" != "true" ]] && workshop_save_state "$state_key" "running"
            ;;
    esac
done

# ─── Post-Deploy ─────────────────────────────────────────────────────────────

if [[ "$WS_DRY_RUN" != "true" && "$ACTION" == "provision" ]]; then
    workshop_save_state "state" "deployed"
    workshop_generate_deployment_info "{{PROJECT_NAME}}" "$GUID" "agnosticd-infra"

    echo ""
    workshop_log OK "Infrastructure $ACTION complete!"
    workshop_log INFO "GUID: $GUID | Environment: $ENV_NAME"
    workshop_log INFO "Deployment info: deployment_info.txt"
    workshop_log INFO "Logs: $LOGFILE"
elif [[ "$WS_DRY_RUN" != "true" ]]; then
    workshop_log OK "Infrastructure $ACTION complete (GUID: $GUID, env: $ENV_NAME)"
fi
