#!/usr/bin/env bash
# teardown.sh — Destroy infrastructure for {{PROJECT_NAME}}
# Generated by rhel-devops-skills scaffold (type: agnosticd-infra)
#
# Destroys configs in reverse order.
#
# Usage:
#   ./scripts/teardown.sh                  # Destroy default environment
#   ./scripts/teardown.sh --env prod       # Destroy specific environment
#   ./scripts/teardown.sh --dry-run        # Preview
#   ./scripts/teardown.sh --yes            # Skip confirmation

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_ROOT"

WORKSHOP_LIB="${WORKSHOP_LIB:-$HOME/.local/share/rhel-devops-skills}"
# shellcheck source=/dev/null
source "$WORKSHOP_LIB/workshop-common.sh"

# ─── Argument Parsing ────────────────────────────────────────────────────────

WS_DRY_RUN=false
WS_YES=false
ENV_NAME=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --env)       ENV_NAME="${2:-}"; shift 2 ;;
        --dry-run)   WS_DRY_RUN=true; shift ;;
        --yes|-y)    WS_YES=true; shift ;;
        --confirm)   shift ;;
        *) echo "Unknown option: $1"; exit 2 ;;
    esac
done

export WS_DRY_RUN WS_YES

# ─── Load Config ─────────────────────────────────────────────────────────────

workshop_load_config

CONFIG_NAMES="${WS_CFG_CONFIG_NAMES:-{{CONFIG_NAMES}}}"
ENVIRONMENTS="${WS_CFG_ENVIRONMENTS:-{{ENVIRONMENTS}}}"
AGD_ROOT="${WS_CFG_AGD_ROOT:-{{AGD_ROOT}}}"
ACCOUNT="${WS_CFG_ACCOUNT:-sandbox}"

if [[ -z "$ENV_NAME" ]]; then
    ENV_NAME="${ENVIRONMENTS%%,*}"
fi

IFS=',' read -ra CONFIGS <<< "$CONFIG_NAMES"

# ─── Pre-flight ──────────────────────────────────────────────────────────────

GUID="$(workshop_get_guid)"
if [[ -z "$GUID" ]]; then
    workshop_log ERROR "No deployment state found. Nothing to destroy."
    exit 1
fi

workshop_state_lock || exit 1
trap 'workshop_state_unlock' EXIT

LOGFILE="$(workshop_init_logging "$GUID")"
workshop_log INFO "Teardown started: GUID=$GUID, env=$ENV_NAME"
workshop_log INFO "Configs (reverse order): ${CONFIGS[*]}"

# ─── Confirmation ────────────────────────────────────────────────────────────

if [[ "$WS_DRY_RUN" != "true" ]]; then
    echo ""
    workshop_log WARN "This will DESTROY ($ENV_NAME environment):"
    for config in "${CONFIGS[@]}"; do
        echo "  - $config"
    done
    echo "  - GUID: $GUID"
    echo ""

    if ! workshop_confirm "Proceed with teardown?"; then
        workshop_log INFO "Teardown cancelled."
        exit 0
    fi
fi

# ─── Destroy in reverse order ────────────────────────────────────────────────

for ((i=${#CONFIGS[@]}-1; i>=0; i--)); do
    config="$(echo "${CONFIGS[$i]}" | xargs)"
    local_vars="vars/${ENV_NAME}.yml"
    agd_vars="$AGD_ROOT/agnosticd-v2-vars/${config}.yaml"
    vars_file="${local_vars}"

    if [[ ! -f "$vars_file" ]]; then
        vars_file="$agd_vars"
    fi

    workshop_agd_destroy "$config" "$vars_file" "$GUID"

    if [[ "$WS_DRY_RUN" != "true" ]]; then
        workshop_save_state "config_${config}_${ENV_NAME}_status" "destroyed"
    fi
done

# ─── Cleanup ─────────────────────────────────────────────────────────────────

if [[ "$WS_DRY_RUN" != "true" ]]; then
    workshop_save_state "state" "destroyed"
    workshop_save_state "destroyed_at" "$(date -Iseconds)"

    echo ""
    workshop_log OK "Teardown complete (GUID: $GUID, env: $ENV_NAME)"
    workshop_log INFO "Logs: $LOGFILE"
fi
